Simplify Navbar
SlugPath/SlugPath pull request #271
Opened 2024-02-21 22:00 UTC by zacktraczyk

Simplified/condensed navbar, moved feedback link to bottom.

closes #270

2024-02-23 01:43 UTC, fercevik729 requested changes
Update logo in exportModal to new logo

2024-02-23 18:56 UTC, oluthje commented
The toggle light/dark mode button should respond visually when the user hovers over it, just like any other button in the app does.

2024-02-24 15:04 UTC, oluthje approved these changes

2024-02-24 20:41 UTC, fercevik729 approved these changes

2024-02-24 20:50 UTC, merged